### ISSUE TITLE
travis fails with undefined symbol PyInterpreterState_GetID on travis for pypy3.9

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/pyina#65]
See: https://app.travis-ci.com/github/uqfoundation/pyina/jobs/613166138
Travis fails on: `from mpi4py import MPI` with undefined symbols on a `mpich` build on travis for pypy3.9.

**Comment by mmckerns** [comment]
More specifically, after the build "succeeds", then on importing it fails:
```
++python pyina/tests/test_ezmap.py
Traceback (most recent call last):
  File "pyina/tests/test_ezmap.py", line 109, in <module>
    test_ezmap()
  File "pyina/tests/test_ezmap.py", line 96, in test_ezmap
    from pyina.ez_map import ez_map as _map
  File "/home/travis/virtualenv/pypy3.9-7.3.9/lib/pypy3.9/site-packages/pyina/__init__.py", line 27, in <module>
    import pyina.launchers as launchers
  File "/home/travis/virtualenv/pypy3.9-7.3.9/lib/pypy3.9/site-packages/pyina/launchers.py", line 85, in <module>
    from pyina.mpi import Mapper, defaults
  File "/home/travis/virtualenv/pypy3.9-7.3.9/lib/pypy3.9/site-packages/pyina/mpi.py", line 60, in <module>
    from mpi4py import MPI
ImportError: /home/travis/virtualenv/pypy3.9-7.3.9/lib/pypy3.9/site-packages/mpi4py/MPI.pypy39-pp73-x86_64-linux-gnu.so: undefined symbol: PyInterpreterState_GetID
```
